version: '3.2'

services: 
  web: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Karoke
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    command: ["nginx", "-g", "daemon off;"]
    